import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Archive All Post ",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased text-gray-800">
        <Navbar />
        <main className="container px-8 mx-auto xl:px-5 max-w-screen-lg py-5 lg:py-8">
          {children}
        </main>
        <Footer/> 
      </body>
    </html>
  );
}
